version: '3'
services:
  mongo:
    image: mongo:latest
    restart: always
    #    environment:
    #      MONGO_INITDB_ROOT_USERNAME: root
    #      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017-27019:27017-27019"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8888:8081"

  spring-gremlins:
    image: spring-docker
    restart: always
    network_mode: host
    ports:
      - "8086:8086"